# Generated by Django 3.2.5 on 2021-07-26 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='produts',
            name='img',
            field=models.ImageField(default='', upload_to='shop/images'),
        ),
        migrations.AddField(
            model_name='produts',
            name='price',
            field=models.ImageField(default=0, upload_to=''),
        ),
        migrations.AddField(
            model_name='produts',
            name='scategory',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='produts',
            name='subcategory',
            field=models.CharField(default='', max_length=50),
        ),
    ]
