# Generated by Django 3.2.5 on 2021-07-26 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_alter_produts_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='produts',
            old_name='secs',
            new_name='Decs',
        ),
        migrations.RenameField(
            model_name='produts',
            old_name='scategory',
            new_name='category',
        ),
    ]
