# Generated by Django 3.2.5 on 2021-08-10 22:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_contact'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='contact',
            new_name='contact_user',
        ),
    ]
